# Generated by Django 6.0.7 on 2026-07-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocatalogo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
