# Generated by Django 6.1 on 2026-08-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tenant_dias_garantia_servicio_and_more'),
        ('inventario', '0002_serviciocatalogo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=2, help_text='Punto de reorden: El sistema alertará cuando el stock baje de este número.'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('dias_visita', models.CharField(blank=True, help_text='Ej. Pasa los Lunes y Jueves por la mañana', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_surtidos', to='inventario.proveedor'),
        ),
    ]
