# Generated by Django 6.1 on 2026-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='modulo_citas',
            field=models.BooleanField(default=False, help_text='¿Paga el módulo de agenda/citas?'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='modulo_facturacion',
            field=models.BooleanField(default=False, help_text='¿Paga facturación electrónica?'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='modulo_inventario_avanzado',
            field=models.BooleanField(default=False, help_text='¿Paga control de stock y proveedores?'),
        ),
    ]
