# Generated by Django 6.1 on 2026-08-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_modulo_citas_tenant_modulo_facturacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='dias_garantia_servicio',
            field=models.IntegerField(default=30),
        ),
    ]
