# Generated by Django 6.1 on 2026-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_dias_garantia_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='dias_garantia_servicio',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='dias_garantia_servicio',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='dias_para_recordatorio',
            field=models.IntegerField(default=180),
        ),
    ]
