# Generated by Django 6.1 on 2026-08-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tenant_dias_garantia_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='modulo_garantias',
            field=models.BooleanField(default=False, help_text='Detección automática de garantías'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='modulo_punto_venta',
            field=models.BooleanField(default=False, help_text='Acceso a la app de escritorio'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='modulo_retencion',
            field=models.BooleanField(default=False, help_text='CRM de recompras automáticas'),
        ),
    ]
