# Generated by Django 6.1 on 2026-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_modulo_garantias_tenant_modulo_punto_venta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('contactado', models.BooleanField(default=False, help_text='Marcar cuando el equipo de ventas ya hizo el seguimiento.')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
