# Generated by Django 6.0.7 on 2026-07-28 17:32

import django.db.models.deletion
import taller.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('DIAGNOSTICO', 'En Diagnóstico'), ('REPARACION', 'En Reparación'), ('LISTA', 'Lista para Entrega'), ('ENTREGADA', 'Entregada')], default='RECIBIDA', max_length=15)),
                ('notas_cliente', models.TextField(blank=True, help_text='Problema reportado por el cliente')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas privadas del mecánico')),
                ('token_publico', models.CharField(default=taller.models.generar_token_publico, max_length=64, unique=True)),
                ('pagada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.bicicleta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='taller.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.serviciocatalogo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='taller.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.iteminventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='taller.ordentrabajo')),
            ],
        ),
    ]
