# Generated by Django 6.1 on 2026-08-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='taller.ordentrabajo')),
            ],
        ),
    ]
