# Generated by Django 6.1 on 2026-08-17 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('taller', '0004_cargoorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='bicicleta',
            field=models.ForeignKey(blank=True, help_text='Vincular si ya es cliente recurrente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.bicicleta'),
        ),
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
