# Generated by Django 6.1 on 2026-08-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_cita_bicicleta_cita_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoorden',
            name='estado_aprobacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de respuesta'), ('APROBADO', 'Aprobado por el cliente'), ('RECHAZADO', 'Rechazado por el cliente')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='cargoorden',
            name='evidencia_foto',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias_taller/'),
        ),
        migrations.AddField(
            model_name='cargoorden',
            name='evidencia_nota',
            field=models.TextField(blank=True, help_text='Ej. El balero presenta fisuras graves que comprometen la seguridad.', null=True),
        ),
        migrations.AddField(
            model_name='cargoorden',
            name='requiere_aprobacion',
            field=models.BooleanField(default=False, help_text='Marcar si es un hallazgo nuevo durante el diagnóstico'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida (En fila)'), ('DIAGNOSTICO', 'En Diagnóstico'), ('ESPERANDO_APROBACION', 'Esperando Aprobación'), ('REPARACION', 'En Reparación'), ('REPARADA', 'Reparada (Lista para entrega)'), ('ENTREGADA', 'Entregada / Cobrada'), ('CANCELADA', 'Cancelada / Devuelta sin reparar')], default='RECIBIDA', max_length=20),
        ),
    ]
