# Generated by Django 6.1 on 2026-08-19 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_cargoorden_estado_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='uuid_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
