# Generated by Django 6.1 on 2026-08-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_ordentrabajo_uuid_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='es_posible_garantia',
            field=models.BooleanField(default=False, help_text='El sistema lo marca en True si la bici tuvo un servicio reciente.'),
        ),
    ]
