# Generated by Django 6.1 on 2026-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_ordentrabajo_es_posible_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_proximo_servicio',
            field=models.DateField(blank=True, help_text='Fecha calculada para el siguiente mantenimiento.', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
